dist: bionic
language: cpp
compiler:
    - clang
before_install:
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
    - sudo add-apt-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' -y
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
    - sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main' -y
    - sudo apt-get update -q
    - sudo apt-get install -y
      cmake ninja-build
      clang-9 lld-9 libc++-9-dev libc++abi-9-dev
    - dpkg-query -L cmake
    - whereis cmake
    - sudo rm /usr/local/cmake
    - sudo rm -rf /usr/local/cmake-3.12.4
    - cmake --version
    
    - if [ ! -f vcpkg/vcpkg ]; then
        git clone https://github.com/microsoft/vcpkg.git;
        cd vcpkg;
        ./bootstrap-vcpkg.sh;
        cat toolsrc/build.rel/CMakeFiles/CMakeOutput.log;
        cat toolsrc/build.rel/CMakeFiles/CMakeError.log;
        cd ..;
      fi
    - export CXX=clang++-9; export CC=clang-9;
    - export CXXFLAGS="-stdlib=libc++"; export LDFLAGS="-stdlib=libc++ -fuse-ld=lld";
    - cd vcpkg
    - git pull
    - ./vcpkg install fmt lmdb nlohmann-json catch2 range-v3 clara reproc
    - ./vcpkg upgrade --no-dry-run
    - rm -rf downloads buildtrees packages
    - cd ..
    
#    - if [ ! -f llvm-build/bin/clang-scan-deps ]; then
#        git clone --depth 1 https://github.com/stevencpp/llvm-project.git;
#        mkdir -p llvm-build && cd llvm-build;
#        cmake -G "Ninja" -DLLVM_ENABLE_PROJECTS='clang' -DCMAKE_BUILD_TYPE=Release ../llvm-project/llvm;
#        ninja clang-scan-deps;
#        cd ..;
#      fi
    - curl -fsSL -o clang-scan-deps "https://drive.google.com/uc?export=download&id=1JspP_ML6WS1b6MZdr5NGvXAkRfWQdgr1"
    - chmod +x clang-scan-deps
cache:
    - ccache
    - directories:
        /home/travis/build/stevencpp/cpp_modules/vcpkg
        /home/travis/build/stevencpp/cpp_modules/llvm-build/bin
script:
    - mkdir build &&
      cd build &&
      cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake"
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        -G "Ninja" .. &&
      ninja &&
      cd src/test &&
      ./cppm_test [lmdb],[scanner],[gen_ninja]
        --clang_scan_deps_path=../../../clang-scan-deps
        --clang_c_path=`which clang-9`
        --clang_cxx_path=`which clang++-9`
        --ninja_path=`which ninja`
        --ninja_fork_path=../../_deps/ninja-build/ninja