image: Visual Studio 2019

cache:
- c:\tools\vcpkg\installed\
- C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ifc\x64
- C:\PROJECTS\CPP-MODULES\downloads
- C:\PROJECTS\CPP-MODULES\ninja
    
build_script:
- cmd: >
    if not exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ifc\x64\Debug"
    "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vs_installer.exe" modify --quiet --norestart
    --installPath="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community"
    --add Microsoft.VisualStudio.Component.VC.Modules.x86.x64
    
    vcpkg install fmt:x86-windows lmdb:x86-windows nlohmann-json:x86-windows
    catch2:x86-windows range-v3:x86-windows clara:x86-windows reproc:x86-windows

    mkdir build
    
    cd build
    
    cmake -DCMAKE_TOOLCHAIN_FILE="c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
    -G "Visual Studio 16 2019" -A "Win32"
    -DCMAKE_INSTALL_PREFIX="C:\Program Files\cpp_modules"
    ..
    
    cmake --build . --config "Debug" --parallel
    
    cmake --install . --config "Debug"
    
test_script:
- cmd: >
    cd ..
    
    if not exist downloads
    mkdir downloads
    
    cd downloads
    
    if not exist "clang-scan-deps.exe"
    appveyor DownloadFile "https://drive.google.com/uc?export=download&id=1xHRCY_eF5uPrW2kNMj1LyXeCCfFFVNia" 
    -FileName "clang-scan-deps.exe"
    
    if exist clang-cl.exe del clang-cl.exe
    
    copy /Y * "C:\Program Files\LLVM\bin"
    
    cd ..
    
    appveyor DownloadFile "https://prereleases.llvm.org/win-snapshots/LLVM-10.0.0-r375090-win64.exe" 
    -FileName "LLVM.exe"
    
    "C:\Program Files\7-Zip\7z.exe" x LLVM.exe -y -ollvm bin\clang.exe bin\clang-cl.exe bin\clang++.exe
    
    copy /Y llvm\bin\* "C:\Program Files\LLVM\bin"
    
    if not exist ninja
    git clone https://github.com/ninja-build/ninja.git &&
    cd ninja &&
    cmake -G "Visual Studio 16 2019" -A "x64" . &&
    cmake --build . --config "Release" --parallel &&
    cd ..
    
    cd build\src\test
    
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
    
    .\Debug\cppm_test.exe [scanner],[msbuild],[lmdb],[gen_ninja]
    --ninja_path=../../../ninja/Release/ninja.exe